package com.feko.generictabletoprpg.tracker

import com.feko.generictabletoprpg.common.InsertOrUpdateUseCase

interface InsertOrUpdateTrackedThingGroupUseCase : InsertOrUpdateUseCase<TrackedThingGroup>